#security:
#  oauth2:
#    client:
#      clientId: login_client
#      clientSecret: secret
#      accessTokenUri: https://lab-demo.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/token
#      userAuthorizationUri: https://lab-demo.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/authorize
#      tokenName: oauth_token
#    resource:
#      userInfoUri: https://lab-demo.predix-uaa.run.aws-usw02-pr.ice.predix.io/userinfo
#spring:
#  resources:
#    chain:
#      enabled: true
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG