debug: false

server:
  tomcat.max-threads: 10
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

uaa:
  tokenservices:
    store-claims: true
    trusted-issuer-ids-regex: ^${vcap.services.uaa-lab.credentials.issuerId}$

security:
  basic:
    enabled: false

cors:
  xhr:
    allowed:
      uris: ^/v2/api-docs$
      origins: ^.*\\.predix\\.io$
      headers: Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers,Authorization
    controlmaxage: 3600

---

spring:
  profiles: dev
  main:
    banner-mode: off

security:
  ignored: /**

debug: true

